apiVersion: apps/v1
kind: Deployment
metadata:
  name: OnePlusOne
  labels:
    app: OnePlusOne
spec:
  replicas: 1
  selector:
    matchLabels:
      app: OnePlusOne
  template:
    metadata:
      labels:
        app: OnePlusOne
    spec:
      containers:
        - name: OnePlusOne
          image: username/OnePlusOne:latest
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5